- name: conditions
  hosts: frontend
  become: yes
  vars:
    number: 800
  tasks:
    - name: print the number is greather than 80
      ansible.builtin.debug:
        msg: "Given number is {{number}}"
      when: number > 100