- name: ansible datatypes
  hosts: frontend
  become: yes
  vars:
    name: "venkat"
    age: "29"
    Tools:
    - Linux
    - shell
    - ansible
    - terraform
    Concepts:
      CI: Jenkins
      Scripting: "python, yaml, shell"
  tasks:
    - name: print the vars and Tools
      ansible.builtin.debug:
        msg: "The vars are {{name}},{{age}} and tools are {{Tools}}"