- name: print information
  hosts: local
  connection: local
  vars-files:
    - information.yaml
  tasks:
    - name: print person information
      ansible.builtin.debug:
        msg: "i am {{name}}"