- name: loops topic
  hosts: frontend
  tasks:
    - name: prints names
      ansible.builtin.debug:
        msg: "Hello, {{ item }}"
      loop:
        - suresh
        - ramesh
        - venkat
        - kohli