- name: loops conecpt
  hosts: frontend
  become: yes
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: "Hello, {{items}}"
      loop:
        - suresh
        - Ramesh
        - Joseph