- name: play level variables
  hosts: local
  connection: local
  vars:
    name: gowri
    studied: pg
    profession: software
  tasks:
    - name: print information
      # Debug function will print
      ansible.builtin.debug:
        msg: " hello, this is {{name}}, i graudtaed {{studied}}, my occupation is {{profession}}"
